watched:
  - name: torrent
    dest: "T:\\torrents\\"
    extension: torrent
    from: "c:\\users\\julien\\Downloads"

# watched: 
# - 
#   torrent: 
#     dest: "T:\\torrents\\"
#     extension: torrent
#     from: "c:\\users\\julien\\Downloads"
# - 
#   torrent2: 
#     dest: "T:\\torrents\\"
#     extension: torrent
#     from: "c:\\users\\julien\\Downloads"

# tags:
# - name: "pet"
#   description: "Everything about your Pets"
#   externalDocs:
#     description: "Find out more"
#     url: "http://swagger.io"
# - name: "store"
#   description: "Access to Petstore orders"
# - name: "user"
#   description: "Operations about user"
#   externalDocs:
#     description: "Find out more about our store"
#     url: "http://swagger.io"